language: android

jdk:
  - oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-29.0.3
    # The SDK version used to compile your project
    - android-29
    # Additional components
    - extra-android-m2repository
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew clean assemble
  - ./gradlew test
  - ./gradlew assembleAndroidTest

notifications:
  email: false

sudo: false
